apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ include "workflow-builder.fullname" . }}
  labels:
    {{- include "workflow-builder.labels" . | nindent 4 }}
    release: prometheus
spec:
  selector:
    matchLabels:
      {{- include "workflow-builder.selectorLabels" . | nindent 6 }}
      platformatic.dev/monitor: prometheus
  podMetricsEndpoints:
  - honorLabels: false
    interval: 15s
    port: metrics
    path: /metrics
    relabelings:
    - action: replace
      sourceLabels:
      - __meta_kubernetes_pod_label_app_kubernetes_io_name
      targetLabel: name
    - action: replace
      sourceLabels:
      - __meta_kubernetes_pod_label_app_kubernetes_io_instance
      targetLabel: instance


